sonar.projectKey=gitroomhq_instapost-app
sonar.projectName=InstaPost App
sonar.projectDescription=Premium Open-Source Social Media Scheduler and Automation Suite

# Scan Performace
sonar.javascript.node.maxspace=24576
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/*.spec.ts,**/*.test.ts,*.png
